image: docker:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

services:
  - docker:dind

test:
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS docker.io
    - apk add --no-cache make docker-compose curl
  script:
    - make runConfigDocker
    - sleep 30
    - make docker-test
  artifacts:
    paths:
      - tmp
    expire_in: 1 week
